#!/bin/bash

help () {
	echo 'USAGE: spin [-v] [-p] [-h <max heap size>] <num threads> <built-tests-dir> <matcher> [dependencies]...'
	echo -e "\t"'-v [OPTIONAL]: if present this flag specifies to run in verbose logging mode.'
	echo -e "\t"'-p [OPTIONAL]: if present this flag specifies to persist the test results in a database.'
	echo -e "\t"'-h <max heap size> [OPTIONAL]: if present this flag specifies the max heap size to use (eg. 64M)'
	echo -e "\t"'num threads: the number of threads to use to run the tests with.'
	echo -e "\t"'built-tests-dir: a directory that contains all of the built .class test files to be run.'
	echo -e "\t"'matcher: the pattern to match Java tests against (eg: Test.java matches files ending with Test.java)'
	echo -e "\t"'dependencies [OPTIONAL]: zero or more .class or .jar files required to run the tests.'
}

function parse () {
	if [ "$1" == '-v' ]
	then
		verbose=true
		num_optionals=$((num_optionals+1))
	elif [ "$1" == '-p' ]
	then
		persist=true
		num_optionals=$((num_optionals+1))
	elif [ "$1" == '-h' ]
	then
		heap_size="$2"
		num_optionals=$((num_optionals+2))
	else
		return 1
	fi
}

# We have 2 non-optional arguments we expect so if given less we fail out.
if [ $# -lt 2 ]
then
	help
	exit 1
fi

# Verify that the python json parser is in the same directory as this script and if not fail out.
if [ ! -f 'json_parser.py' ]
then
	echo 'The json_parser.py script must be placed in the same directory as this script: did not find it.'
	exit 1
fi

# Determine which optional flags have been given.
num_optionals=0
verbose=false
persist=false
heap_size=64M

if [[ "$1" =~ -. ]]
then
	parse "$1" "$2"
	if [ $? -ne 0 ]
	then
		echo "Failed to parse argument: $1"
		help
		exit 1
	fi
fi
if [[ "$2" =~ -. ]]
then
	parse "$2" "$3"
	if [ $? -ne 0 ]
        then
		echo "Failed to parse argument: $1"
                help
                exit 1
        fi
fi
if [[ "$3" =~ -. ]]
then
	parse "$3" "$4"
	if [ $? -ne 0 ]
        then
		echo "Failed to parse argument: $1"
                help
                exit 1
        fi
fi

# Set any system properties required by optional flags.
if [ "$verbose" = true ]
then
	verbose_property='-Denable_logger=true'
else
	verbose_property='-Denable_logger=false'
fi
if [ "$persist" = true ]
then
	persist_property='-Dwrite_to_db=true'
else
	persist_property='-Dwrite_to_db=false'
fi

# Determine the indices of the non-optional arguments.
num_threads_index=$((1+num_optionals))
test_dir_index=$((1+num_threads_index))
matcher_index=$((1+test_dir_index))

# Next argument must be a number, we verify that and this is the number of threads to use.
num_threads=${!num_threads_index}
if ! [[ "$num_threads" =~ ^[0-9]+$ ]]
then
	help
	exit
fi

num_threads_property="-Dnum_threads=$num_threads"
test_dir="${!test_dir_index}"
matcher="${!matcher_index}"

# Collect any given dependencies and then run the program.
dependencies='['
is_first=true
for dependency in ${@:$((matcher_index+1))}
do
	if [ $is_first = true ]
	then
		dependencies="$dependencies"'"'"$(realpath $dependency)"'"'
		is_first=false
	else
		dependencies="$dependencies"',"'"$(realpath $dependency)"'"'
	fi
done
dependencies="$dependencies]"

#TODO: rather than expect a 'dependencies' dir this should be configurable.
classpath='spin-core.jar:'dependencies/*

# Set the database config file path property here. We hardcode this. Note this is only used when -p is given.
dbconfig_property='-Ddb_config_path=./config/db_config.txt'

echo '[spin-singleuse] Starting Spin...' >> output.txt

# Run using the specified max heap size or our default 64MB
# Do a heap dump if an OOM is encountered
# If an OOM is encountered kill the process. Why? So we explicitly exit with a non-zero exit code to indicate failure.
java -Xmx$heap_size -XX:+HeapDumpOnOutOfMemoryError -XX:OnOutOfMemoryError="kill -9 %p" "$verbose_property" "$persist_property" "$dbconfig_property" "$num_threads_property" -cp "$classpath" spin.core.LongLivedEntryPoint &> output.txt &

if [ $? -ne 0 ]
then
	echo 'Failed to start Spin!'
	exit 1
fi

echo '[spin-singleuse] Spin successfully started.' >> output.txt

echo '[spin-singleuse] Waiting for Spin to publish server port' >> output.txt
spin_pid="$(echo $!)"
info_file="$(realpath ~/.spin/info_$spin_pid)"

echo "[spin-singleuse] Expecting to find program info in file: $info_file" >> output.txt
while [ ! -f $info_file ]
do
	echo "[spin-singleuse] Waiting for file to be created: $info_file" >> output.txt
	sleep 1
done

port="$(cat $info_file)"
echo "[spin-singleuse] Found published port: $port" >> output.txt
echo '[spin-singleuse] Running tests...' >> output.txt

echo '{"request_type":"run_suite","body":{"base_dir":"'"$(realpath $test_dir)"'", "matcher":"'"$matcher"'", "dependencies":'"$dependencies"'}}' > input.txt

is_connected=false
while [ $is_connected = false ]
do
	result="$(netcat 127.0.0.1 $port < input.txt)"
	if [ $? -eq 0 ]
	then
		is_connected=true
	else
		sleep 1
	fi
done
rm input.txt

echo '[spin-singleuse] All tests completed.' >> output.txt

is_success="$(python3 json_parser.py --run_suite --is_successful "$result")"
if [ $is_success = true ]
then
	echo "$(python3 json_parser.py --run_suite --get_suite_id "$result")"
else
	echo "$(python3 json_parser.py --run_suite --get_error "$result")"
	exit 1
fi

