#!/bin/bash

help () {
	echo 'USAGE: spin [-v] [-p] <num threads> <built-tests-dir> [dependencies]...'
	echo -e "\t"'-v [OPTIONAL]: if present this flag specifies to run in verbose logging mode.'
	echo -e "\t"'-p [OPTIONAL]: if present this flag specifies to persist the test results in a database.'
	echo -e "\t"'num threads: the number of threads to use to run the tests with.'
	echo -e "\t"'built-tests-dir: a directory that contains all of the built .class test files to be run.'
	echo -e "\t"'dependencies [OPTIONAL]: zero or more .class or .jar files required to run the tests.'
}

# We have 2 non-optional arguments we expect so if given less we fail out.
if [ $# -lt 2 ]
then
	help
	exit 1
fi

# Determine which optional flags have been given.
num_optionals=0
if [ "$1" == '-v' ]
then
	if [ "$2" == '-p' ]
	then
		verbose=true
		persist=true
		num_optionals=2
	else
		verbose=true
		persist=false
		num_optionals=1
	fi
elif [ "$1" == '-p' ]
then
	if [ "$2" == '-v' ]
	then
		help
		exit 1
	fi
	verbose=false
	persist=true
	num_optionals=1
fi

# Set any system properties required by optional flags.
if [ "$verbose" = true ]
then
	verbose_property='-Denable_logger=true'
else
	verbose_property='-Denable_logger=false'
fi
if [ "$persist" = true ]
then
	persist_property='-Dwrite_to_db=true'
else
	persist_property='-Dwrite_to_db=false'
fi

# Determine the indices of the non-optional arguments.
num_threads_index=$((1+num_optionals))
test_dir_index=$((1+num_threads_index))

# Next argument must be a number, we verify that and this is the number of threads to use.
num_threads=${!num_threads_index}
if ! [[ "$num_threads" =~ ^[0-9]+$ ]]
then
	help
	exit
fi

num_threads_property="-Dnum_threads=$num_threads"
test_dir="${!test_dir_index}"
num_tests=0

# Grab all test files in the given test base directory. We consider a test file a file ending with Test.class.
for file in $(find "$test_dir" -type f)
do
	if [[ $(realpath $file) == *"Test.class" ]]
	then
		tests="$tests $(realpath $file)"
		num_tests=$((num_tests+1))
	fi
done

# Collect any given dependencies and then run the program.
for dependency in ${@:$((test_dir_index+1))}
do
	dependencies="$dependencies $(realpath $dependency)"
done

if [ "$persist" = true ]
then
	classpath='spin-singleuse.jar:junit-4.12.jar:postgresql-42.2.12.jar'
else
	classpath='spin-singleuse.jar:junit-4.12.jar'
fi

java "$verbose_property" "$persist_property" "$num_threads_property" -cp "$classpath" spin.core.singleuse.SingleUseEntryPoint "$(realpath $test_dir)" "$num_tests" $tests $dependencies
