version: 2
jobs:
   build:
     docker:
       - image: circleci/openjdk:9.0.4-jdk
     steps:
       - checkout
       - run:
           command: |
             ant build-singleuse
   demo:
     docker:
       - image: circleci/openjdk:9.0.4-jdk
     steps:
       - checkout
       - run:
           command: |
             ./pack.sh && cd pack && ./spin -v 4 build/test build/src lib/*
workflows:
  version: 2
  build_and_demo:
    jobs:
    - build:
       filters:
         branches:
           only: 
             - master
             - dev
    - demo:
       filters:
         branches:
           only:
             - master
             - dev
